Update permissions so that dependabot has permission to run CI
The CI fails with
```
 success compile gatsby files - 1.275s
process.env.NODE_ENV production
error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.

  Error: Contentful spaceId and the access token need to be provided.
```